import type { CardTemplate } from "@/types/card";

export const templates: CardTemplate[] = [
  {
    id: "atelier-noir",
    title: "Atelier Noir",
    category: "Business",
    audience: "Founders, consultants, and luxury service studios",
    palette: ["#07080d", "#f8fafc", "#14b8a6", "#f4c95d"],
    finish: "foil",
    size: "standard",
    priceFrom: 3900,
    preview: { front: "Black soft-touch card with teal foil mark", back: "Minimal contact grid" },
  },
  {
    id: "garden-vow",
    title: "Garden Vow",
    category: "Wedding",
    audience: "Modern wedding invitations with photo integration",
    palette: ["#fff7ed", "#2f3e34", "#d8a48f", "#f7c59f"],
    finish: "emboss",
    size: "invitation",
    priceFrom: 7900,
    preview: { front: "Editorial floral invite", back: "RSVP and venue panel" },
  },
  {
    id: "prism-vip",
    title: "Prism VIP",
    category: "VIP",
    audience: "Events, clubs, creators, and private memberships",
    palette: ["#0f172a", "#38bdf8", "#fb7185", "#f8fafc"],
    finish: "spot-uv",
    size: "standard",
    priceFrom: 5900,
    preview: { front: "Iridescent VIP credential", back: "QR access and terms" },
  },
  {
    id: "cafe-ledger",
    title: "Cafe Ledger",
    category: "Loyalty",
    audience: "Restaurants, salons, gyms, and local shops",
    palette: ["#101113", "#fafafa", "#84cc16", "#f97316"],
    finish: "matte",
    size: "standard",
    priceFrom: 2400,
    preview: { front: "Stamped reward layout", back: "Offer and barcode" },
  },
  {
    id: "identity-pro",
    title: "Identity Pro",
    category: "Employee",
    audience: "Teams that need secure ID cards and badges",
    palette: ["#f8fafc", "#111827", "#2563eb", "#14b8a6"],
    finish: "soft-touch",
    size: "id",
    priceFrom: 4500,
    preview: { front: "Photo badge with role hierarchy", back: "Security strip and QR" },
  },
  {
    id: "neon-birthday",
    title: "Neon Birthday",
    category: "Event",
    audience: "Birthday parties, launches, and social events",
    palette: ["#111827", "#a78bfa", "#22d3ee", "#fef08a"],
    finish: "spot-uv",
    size: "invitation",
    priceFrom: 3400,
    preview: { front: "Photo-first event invitation", back: "Map, RSVP and QR" },
  },
];

export const pricing = [
  { name: "Creator", price: "$19", details: "Design exports, 20 projects, AI copy assist" },
  { name: "Studio", price: "$59", details: "Team library, print checks, 3D finish previews" },
  { name: "Scale", price: "$149", details: "Admin controls, brand kits, priority production" },
];
